### ISSUE TITLE
`xbstrap init ..` fails (readme instructions)

### ISSUE THREAD

**Issue by ohenley** [streaksu/Gloire#3]
```
~/3rd/repos/Gloire$ xbstrap init ..
xbstrap: Using pure Python YAML parser
       : Install libyaml for improved performance
Traceback (most recent call last):
  File "/home/henley/adacore/e3/bin/xbstrap", line 8, in <module>
    sys.exit(main())
  File "/home/henley/adacore/e3/lib/python3.9/site-packages/xbstrap/__init__.py", line 898, in main
    do_init(args)
  File "/home/henley/adacore/e3/lib/python3.9/site-packages/xbstrap/__init__.py", line 74, in do_init
    raise RuntimeError("Given src_root does not contain a bootstrap.yml")
RuntimeError: Given src_root does not contain a bootstrap.yml
```

moving to `base-files` works:
```
~/3rd/repos/Gloire$ cd base-files/
henley@henley-Precision-7750:~/3rd/repos/Gloire/base-files$ xbstrap init ..
xbstrap: Using pure Python YAML parser
       : Install libyaml for improved performance
warning: bootstrap.link already exists, skipping...
```

**Comment by streaksu** [comment]
This is related to a typo in the README that was fixed, could you try again with the updated instructions?

**Comment by ohenley** [comment]
yes, this works now.
